README.rst
fixed example string with existing nn config file
=> little readme fix

examples/maze_explorer.py, setup.py, tensorforce/environments/maze_explorer.py
It probably works better via OpenAIGym as `gym.wrappers.Monitor` provides periodic video saving features. Though watching it play I did spot a collision bug in the environment itself.
Pull if you think it adds something, might be a half decent integration example though is already heavily based on OpenAIGym example.
=> Maze Explorer environment

examples/configs/categorical_dqn_agent_visual.json, tensorforce/agents/categorical_dqn_agent.py, tensorforce/models/categorical_dqn_model.py
Adds in the next_state capability to categorical DQN
Fixed some of the configuration parameters that were wrong
Added support for passing in model into CategoricalDQNAgent
**Actions with shape other than () still not supported**
=> Fix categorical dqn

tensorforce/models/categorical_dqn_model.py, tensorforce/tests/test_categorical_dqn_agent.py
Also made a couple of graph optimizations so that tensors that are shared across actions aren't recreated.
=> Fix categorical dqn multi action & target

docs/index.rst, examples/configs/categorical_dqn_agent_visual.json, examples/openai_gym_async.py, examples/quickstart.py, tensorforce/models/model.py
Sometimes "loglevel" was used which made it ignored.
=> Use "log_level" everywhere

tensorforce/tests/test_dqn_agent.py
Offending commit: https://github.com/reinforceio/tensorforce/commit/b0fd7d13ff1392c60dfef432bfea7a7dd035f71f
=> LSTM regression test

tensorforce/core/networks/layers.py
Fix variable names of linear layers. (W & b)
=> Linear layer variable names

examples/openai_gym_async.py, examples/openai_universe.py
Fix examples to use log_levels from util
=> Fix log_levels comes from util

tensorforce/models/dqn_nstep_model.py, tensorforce/tests/test_dqn_nstep_agent.py, tensorforce/util.py
util.cumulative_discount now supports ndarrays for cumulative_start
=> Multi action support for DQN Nstep.

examples/ale.py, examples/lab_main.py, examples/maze_explorer.py, examples/openai_gym.py, examples/openai_gym_async.py, examples/openai_universe.py, tensorforce/execution/runner.py
Adds calculation of number of timesteps per second to examples (and runner) so it's easy to see algorithm speed
=> Add steps per second to runner & examples

tensorforce/agents/agent.py, tensorforce/execution/runner.py, tensorforce/execution/threaded_runner.py, tensorforce/models/model.py
Adds saving episode rewards to tensorboard (if using a summary writer)
=> Episode reward summary in tensorboard

tensorforce/core/networks/layers.py, tensorforce/models/model.py
For dense, conv2d, lstm layers
=> Add layer activations to summaries gteq level 3

tensorforce/contrib/ale.py
Uses np.copy otherwise it was just returning a pointer so all states would be the same.
Add action names
=> Fix ALE state return

examples/openai_gym_async.py
Alex Kuhnle [mentioned on reddit](https://www.reddit.com/r/MachineLearning/comments/6mnp9d/ptensorforce_a_tensorflow_library_for_applied/dk9659h/) how to run this sample. Couldn't find similar documentation in the codebase, found it very helpful so copy/pasting here
=> Add comment on how to run openai_async.py example

tensorforce/core/optimizers/__init__.py, tensorforce/core/optimizers/tf_optimizer.py
(Close at your digression) Seems like lotta love for Nadam optimizer recently, which is kinda Adam+ as I understand it (Adam +"Nesterov accelerated gradient", [overview](http://ruder.io/optimizing-gradient-descent/index.html#nadam)). With Adam being the default/recommended in many of these agents, might be a boost.
=> For consideration: add Nadam SGD optimizer

tensorforce/config.py, tensorforce/core/networks/layers.py
Now we can write a modified Configuration to disk and when it loads it's equal (via one.as_dict() == other.as_dict()) to the original object.
=> Added to_json() and as_dict() Configuration helpers for easier output of Configurations.

tensorforce/core/memories/replay.py
Fix the bug that replay.get_batch may get wrong next_states when sample the last observation ( #138 )
=> Fix bug in replay.get_batch (#138)

tensorforce/core/optimizers/__init__.py, tensorforce/core/optimizers/tf_optimizer.py
I personally found it out-performed Adam for all my local stuff in #master, see how it goes in #dev
=> re-add Nadam optimizer

tensorforce/core/networks/layer.py
Allows having different width than height (for non-square windows) in Conv2D
=> (for consideration) Conv2d: allow separate width/height values for window, stride

tensorforce/core/networks/layers.py
=> layered-network-builder: enable conv2d layer nonsquare window

docs/preprocessing.md, tensorforce/agents/agent.py, tensorforce/core/preprocessing/preprocessing.py
https://github.com/reinforceio/tensorforce/pull/180 but for Preprocessing
=> Preprocessing.from_config calls => Preprocessing.from_spec

tensorforce/core/networks/layer.py
Looks like a typo when refactoring bias and bias init
=> bias vs bias_init

tensorforce/core/networks/layer.py
Some merges walked on each other, here's some small fixes to Dueling
=> Fixes to Dueling layer

tensorforce/contrib/openai_gym.py
Fix reset() when gym monitor enabled (see: https://github.com/rll/rllab/commit/4fd25fe7a31388fed3e005c86bee9b1c75e4df1d).
=> Fix reset() when gym monitor enabled

docs/agents_models.md
fix a link in _building your own agent_ part of doc
=> fix a broken link

SUMMARY_SPEC.md
Add summary_spec description in Markdown format
=> summary_spec description

docs/environments.md, examples/unreal_engine_game.py, setup.py, tensorforce/__init__.py, tensorforce/agents/agent.py, tensorforce/contrib/remote_environment.py, tensorforce/contrib/state_settable_environment.py, tensorforce/contrib/unreal_engine.py, tensorforce/environments/environment.py, tensorforce/exception.py, tensorforce/models/distribution_model.py
Added Support for Unreal Engine 4-based Environment instances to TensorForce.
UE4 Envs can either be run in the UE4 editor (rendered/simulated/"watching" mode) or run headlessly on Linux (parallelized/"real" mode).
A UE4 Plugin ("Engine2Learn") is needed from github.com/ducandu/engine2learn repo in order to convert a UE4 game into a reinforcement learnable environment.
=> Unreal Engine 4 Support

examples/ale.py
Nothing ever calls agent.save_model
Borrowed code from the threaded runner that does the same thing.
=> ale.py --save never actually saves

tensorforce/agents/agent.py, tensorforce/core/networks/complex_network.py, tensorforce/core/networks/network.py, tensorforce/models/distribution_model.py, tensorforce/models/model.py
This PR will return logits via call to agent act() if include_logits=True.
Not sure if there are other parts of the code that need updating.  I could only find the "distribution_model" to be responsible for logits.
=> First look at optional logits return

tensorforce/core/networks/layer.py, tensorforce/models/model.py
I implement MSRA weight initialization for ReLU nonlinearity, according to https://arxiv.org/pdf/1502.01852.pdf ,
and the implementation refer to the mx.initializer.MSRAPrelu of mxnet.
Also I add a linear weight parameter from Dense pass to Linear.
=> Add MSRA weight initialization

tensorforce/meta_parameter_recorder.py
Update to reflect "summary_spec" -> "summarizer" parameter change in the meta_parameter_recorder.
=> Update meta_parameter_recorder for memory branch merge

docs/summary_spec.md
=> Summar_spec change

examples/configs/cnn_network_2048.json, examples/configs/ppo_cnn.json, examples/game_2048.py, tensorforce/contrib/game_2048.py, tensorforce/core/preprocessors/__init__.py, tensorforce/core/preprocessors/expand_dims.py, tensorforce/core/preprocessors/flatten.py, tensorforce/core/preprocessors/increase_dimension.py
Added Game 2048, to make the game work I have fixed the flatten preprocessor. And I have added a preprocessor to increase dimensionality. This ables you to use a cnn on a 2d matrix.
=> Added Game 2048

tensorforce/contrib/openai_gym.py
Fix integration bug caused by an interface change in OpenAiGym multidiscrete space. Was trying to access properties of the space that do not exist. Bug was discovered against OpenAiGym 0.10.4.
=> OpenAiGym integration bugfix

docs/preprocessing.md
=> Fix typo in preprocessing.md

examples/openai_gym.py
Added options to save trained models, and to enable the visualization of OpenAI Gym.
=> Add a saving and visualization functionality to OpenAI Gym's example

examples/openai_gym.py
=> Removing code from accidental commit (issue #430)

tensorforce/contrib/pygame_learning_environment.py
I forgot to implement visualization, but now it is implemented.
=> visualization implemented

examples/unreal_engine.py, tensorforce/contrib/maze_explorer.py, tensorforce/contrib/openai_universe.py, tensorforce/execution/runner.py, tensorforce/execution/threaded_runner.py, tensorforce/tests/minimal_test.py, tensorforce/tests/test_dqfd_agent.py, tensorforce/tests/test_model_save_restore.py, tensorforce/tests/test_tutorial_code.py
I have finished Refractoring all code from action**s** to action for it to run with arguments. However, some functionality is still not consistent (some test cases).
=> Finished Refractoring

tensorforce/contrib/openai_retro.py
=> OpenAI Retro integration

tensorforce/contrib/openai_gym.py
This threw an exception for me that `name` was undefined. It appears to be just a typo and after this minor change is working for me now.
=> Small typo in openai_gym environment in flatten_state

tensorforce/contrib/ale.py, tensorforce/contrib/game_2048.py, tensorforce/contrib/openai_gym.py, tensorforce/contrib/pygame_learning_environment.py, tensorforce/environments/environment.py
This commit expands on the environment class and clarifies what is returned.
=> Contributed Environments normalized + base environment class docs expanded

examples/unreal_engine.py
A doc fix problem that was raised in #469
=> unreal_engine doc fix

examples/openai_universe.py
minor change to the sample command to run examples/openai_universe.py
=> minor change to the sample command to run openai_universe.py

tensorforce/core/explorations/epsilon_anneal.py, tensorforce/core/networks/layer.py
=> Minor bug fix in Linear Layer and Epsilon anneal exploration

tensorforce/core/optimizers/kfac.py, tensorforce/core/optimizers/kfac_utils.py, tensorforce/core/optimizers/optimizer.py
=> An implementation of KFac Optimization compatible with tensorforce

CONTRIBUTING.md, examples/opensim-rl.py, tensorforce/contrib/osim.py, tensorforce/contrib/vizdoom.py
Reinforcement learning with musculoskeletal models in OpenSim
http://osim-rl.stanford.edu/
=> Add support to OpenSim-RL

examples/configs/mlp2_embedding_flatten_network.json, examples/dm_pycolab.py, examples/extraterrestrial_maurauders.py, tensorforce/contrib/dm_pycolab.py
=> Bindings for Deepmind Pycolab

tensorforce/models/dpg_target_model.py
It's the change I made regarding issue https://github.com/reinforceio/tensorforce/issues/513.
=> Fixes a bug with DDPG

tensorforce/core/networks/layer.py, tensorforce/models/dpg_target_model.py, tensorforce/tests/test_ddpg_agent.py, tensorforce/tests/test_ddpg_agent_custom_critic.py
=> added support for ddpg custom critic network

tensorforce/models/model.py
list_buffer_index_reset_op was not initialized as tensor, hence created problem while indexing.
=> fixed index reset op

docs/preprocessing.md
This pull request makes several critical fixes to the preprocessing documentation to keep up with library updates. I hope it is helpful.
=> Fix preprocessing documentation

tensorforce/execution/threaded_runner.py
=> fix environments tips

tensorforce/core/layers/convolution.py
- Added deconvolutions (actually transposed convolutions) in `convolution.py`
- Changed the method to calculate the output shape of convolutions `get_output_spec`  so that it uses functions from tensorflow, which takes the dilation into account
=> Deconvolution

tensorforce/contrib/socket_remote_env/.gitignore, tensorforce/contrib/socket_remote_env/README.md, tensorforce/contrib/socket_remote_env/RemoteEnvironmentClient.py, tensorforce/contrib/socket_remote_env/dummy_env.py, tensorforce/contrib/socket_remote_env/echo_server.py, tensorforce/contrib/socket_remote_env/launch_parallel_training.py, tensorforce/contrib/socket_remote_env/launch_servers.py, tensorforce/contrib/socket_remote_env/script_launch_parallel.sh, tensorforce/contrib/socket_remote_env/simulation_base/RemoteEnvironmentServer.py, tensorforce/contrib/socket_remote_env/simulation_base/env.py, tensorforce/contrib/socket_remote_env/simulation_base/start_one_server.py, tensorforce/contrib/socket_remote_env/utils.py
@AlexKuhnle this is for pushing as a contribution the socket wrapper classes. Of course this is a bit user-dependent, but hope this can help. This is a slightly more recent setup than from the paper.
=> Socket remote env

tensorforce/execution/runner.py
=> Fix #656 - wrong argument passed by Runner.run()

README.md, setup.py
* Added Classifiers to setup py, mainly language level
* add pypi and python version badge
=> #693  Clarify python version support (#2)

README.md, docs/basics/installation.md
As discussed in #799 . 
Please let me know if I need to change it.
=> Add installation notes for M1 Macs

tensorforce/core/models/tensorforce.py, tensorforce/core/optimizers/optimizer.py
A fix for compatibility with the Keras network wrapper and Tensorboard summaries :)
=> Fixes for Keras network compatibility
