tensorforce/tensorforce

- README.md
An alternative code block syntax is used in order to enable python highlighting of the example. This improves the readability of the example.
> syntax highlighting in readme

- tensorforce/agents/agent.py
I ran into the following error with the example shown in the [blog post](https://reinforce.io/blog/introduction-to-tensorforce/) with DQNAgent.
```
File "/Users/nagachika/work/tensorforce/tensorforce/agents/agent.py", line 178, in act
self.current_internal = self.next_internal
AttributeError: 'DQNAgent' object has no attribute 'next_internal'
```
> initialize internal state at Agent initialization

- tensorforce/models/policy_gradient_model.py
Not sure if this is consistent with other parts of the codebase, but this is how I currently provide custom action distributions for policy gradients:
```actions = dict(continuous=True, distribution=Gaussian())```
where `Gaussian()` can be replaced by any instance of `Distribution`.
> Allow custom distributions in policy gradients

- tensorforce/core/explorations/__init__.py
- tensorforce/core/explorations/epsilon_anneal.py
See #53
Matching Karpathy's implementation.
https://github.com/karpathy/convnetjs/blob/9a3fc7be4d47871497a95dd357e52c9190b2c06d/build/deepqlearn.js#L183
> Epsilon annealing

- examples/ale.py
- tensorforce/environments/ale.py
Adds the Arcade learning environment from https://github.com/mgbellemare/Arcade-Learning-Environment.
I'm not sure where to put reward clipping (if it should be handled by the agent or the environment) so I just put it here.
Additionally the loss of life termination that was used in the Nature DQN is available as a parameter or a negative reward can be set for losing a life.
While frame_skip is the same as runner repeat actions, it's handled by the underlying code of the ALE and is faster than looping in python.
> Add ALE environment

- tensorforce/core/distributions/gaussian.py
- tensorforce/core/networks/layers.py
Initializing weights to zero if a bias is provided seems like a dangerous default if someone decides to explicitly specify a zero bias for some reason. I think this is mostly used by the `Gaussian` distribution to create a zero-mean policy. This PR adds an additional `weights` keyword argument to `linear', which seems cleaner.
> Weights kwargs for linear layer

- tensorforce/core/preprocessing/__init__.py
- tensorforce/core/preprocessing/divide.py
Preprocessing to divide by a constant. Useful if images are returned as uint8 and need to be normalized into the 0-1 range
> Add divide by constant preprocessing

- examples/configs/dqn_agent.json
- examples/configs/dqn_agent_visual.json
- tensorforce/agents/dqfd_agent.py
- tensorforce/agents/dqn_agent.py
- tensorforce/agents/naf_agent.py
- tensorforce/models/q_model.py
Fixes an error where the target variables actually referenced the training variables so the target network would never be updated.
Changed gradient_clipping -> clip_loss to match with @AlexKuhnle changes to q model.
> Fix Q model training variables error

- tensorforce/agents/categorical_dqn_agent.py
- tensorforce/agents/dqfd_agent.py
- tensorforce/agents/dqn_agent.py
- tensorforce/agents/naf_agent.py
- tensorforce/core/networks/layers.py
- tensorforce/core/networks/network.py
- tensorforce/models/categorical_dqn_model.py
- tensorforce/models/dqn_model.py
- tensorforce/models/model.py
- tensorforce/models/q_model.py
- tensorforce/tests/test_categorical_dqn_agent.py
- tensorforce/tests/test_dqfd_agent.py
- tensorforce/tests/test_dqn_agent.py
- tensorforce/tests/test_naf_agent.py
- tensorforce/tests/test_ppo_agent.py
- tensorforce/tests/test_trpo_agent.py
- tensorforce/tests/test_tutorial_code.py
- tensorforce/tests/test_vpg_agent.py
Adds tf_summary_level and tf_summary_interval to configs.
Adds a timestep in model that's incremented each call to get_action
Supports loss, trainable variables and action outputs.
The summary levels I had imagined are as follows:
0. Loss/Loss per action, these summaries are always created so they don't check config.tf_summary_level
1. Network Output, Q values for DQN. I'm not very familiar with policy gradient methods so I wasn't sure what output summary would be most useful and thus didn't write any
2. Trainable Variables, target networks is why I had to add a trainable flag into the layer constructor. The easy way to do this was using tf.trainable_variables, but it could be done in the layer functions and that would remove the need for the trainable flag.
> Initial TensorFlow summaries support

- tensorforce/models/categorical_dqn_model.py
use log(probs + epsilon).
This should be essentially the same thing but using softmax_cross_entropy_with_logits wasn't converging
> Categorical DQN numerical stability

- tensorforce/core/networks/layers.py
Adds a `dropout=_` param to `lstm()`, which if provided wraps `lstm_cell` in a `rnn.DropoutWrapper` for regularization. Feel free to close if there's a smarter way, more for consideration on providing a dropout option for these layers where applicable.
> wrap LSTMCell in DropoutWrapper if dropout param

- tensorforce/core/networks/layers.py
Sorry guys, I may have gotten https://github.com/reinforceio/tensorforce/pull/110 wrong - I think `output_keep_prob` is supposed to be the _opposite_ (or just rename the function arg to `output_keep_prob`). Double check my sanity if you could: [usage](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/DropoutWrapper#__init__)
> DropoutWrapper output_keep_prob=1-dropout, not =dropout

- examples/ale.py
- examples/configs/dqfd_agent.json
- examples/configs/dqn_agent.json
- examples/configs/dqn_agent_visual.json
- examples/configs/dqn_nstep_agent_visual.json
- examples/configs/dqn_universe.json
- examples/threaded_ale.py
- tensorforce/agents/agent.py
- tensorforce/agents/batch_agent.py
- tensorforce/agents/dqfd_agent.py
- tensorforce/agents/memory_agent.py
- tensorforce/agents/random_agent.py
- tensorforce/contrib/ale.py
- tensorforce/core/preprocessing/__init__.py
- tensorforce/core/preprocessing/clip.py
Reward clipping applies to all DQN/A3C agents that I know of so I think it makes sense to put this in the base Agent class. This change supports any type of reward preprocessing as defined in the preprocessing folder (divide, clip [newly added], etc)
Subclasses of Agent must now override _observe(self, reward, terminal) instead of observe. 
Also removes reward clipping from ALE and updates the DQN config files to include reward clipping [-1, 1]
> Add reward preprocessing to base Agent

- tensorforce/config.py
this method was always allowing defaults rather than passing through the method's argument.
> allow_defaults fix in Configuration.from_json()

- tensorforce/core/memories/prioritized_replay.py
If prioritized_replay enters the loop in line 89, it gets the index but not the observation, leading to the error "UnboundLocalError: local variable 'observation' referenced before assignment". This fixes it.
> Fix  'observation' referenced before assignment"

- tensorforce/core/explorations/exploration.py
As w/ all my newbie PRs, feel free to scrap mine & use your own if y'all have a correct solution. Defining exploration in the config gave "Exploration doesn't have from_config()" (ish).
> missing Exploration.from_config

- tensorforce/core/explorations/epsilon_anneal.py
This was using a max of one which led to funny behaviour where it didn't use epsilon [see plot here](https://gist.github.com/wassname/21b0e3c5a7cf97a32d424cd851507fc3). This fixes it.
> max of 1 to max of epsilon

- tensorforce/core/memories/prioritized_replay.py
If the first update is smaller than the batch size them prioritized_replay can go into an infinite loop on lines 93 and 98, this will raise an informative error instead.
> error instead of infinite loop

- tensorforce/core/explorations/epsilon_decay.py
If you plot this is has a half life of 1, independent of epsilon_timesteps. If you plot it you see exploration drop to epsilon_final in ~20 steps. 
This changes it to have a configurable amount of half lives per epsilon_timesteps. [Plots of before and after here](https://gist.github.com/wassname/21b0e3c5a7cf97a32d424cd851507fc3)
> change half_life of 1 to epsilon_timesteps/10

- tensorforce/agents/agent.py
`Exploration.from_config` was removed in https://github.com/reinforceio/tensorforce/commit/1a28dbd61377e0d3b8b3a1c29195bf79837ab192 per https://github.com/reinforceio/tensorforce/pull/171, but it seems calls to that function haven't been replaced w/ `Exploration.from_spec`, resulting in:
```
(btc3) lefnire@lefnire-ubuntu:~/Sites/btc$ python tforce/single.py 
[2017-10-22 08:14:24,523] Making new env: BTC-v0
2017-10-22 08:14:24.602836: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-10-22 08:14:24.603044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 …
```
> Change Exploration.from_config calls to Exploration.from_spec

- tensorforce/agents/agent.py
Might be just my setup, but just in case (feel free to close). I'm getting the following:
```
(btc3) lefnire@lefnire-ubuntu:~/Sites/btc$ python tforce/single.py 
[2017-10-22 08:18:00,634] Making new env: BTC-v0
2017-10-22 08:18:00.714209: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-10-22 08:18:00.714420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.90GiB freeMemory: 2.75GiB
2017-10-22 08:18:00.714437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device …
```
> actions_spec is dict, dot-accessor => key-accessor

- examples/configs/ppo_agent.json
Fixing a trailing comma error in the json specification for ppo_agent
> Update ppo_agent.json. json not valid

- tensorforce/core/baselines/__init__.py
Eh, "PR".. one-liner.. Re: https://github.com/reinforceio/tensorforce/issues/118#issuecomment-340088616. Handy for people using a custom-defined network, rather than `network_builder` ([example](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/tests/test_tutorial_code.py#L226))
> Allows custom baseline network

- tensorforce/execution/threaded_runner.py
Comment from https://github.com/reinforceio/tensorforce/commit/e0dead7ce49935210074ec9d449990c18065f0d4#commitcomment-25330825
>So ThreadedRunner & Runner's reward/terminal order are different (https://github.com/reinforceio/tensorforce/blob/master/tensorforce/execution/runner.py#L95). _This_ here looks like the correct way, according to standard environments, but ThreadedRunner won't run for me where Runner will! I swapped them in this file to double check, and sure enough that fixes it. Something wonky in the Gym wrapper maybe?
>[edit] Ah, sure enough - Gym wrapper swaps them here https://github.com/reinforceio/tensorforce/blob/master/tensorforce/contrib/openai_gym.py#L65. Not sure the thinking on the swap, but it's pretty consistent throughout the codebase - so seems the fix for now is …
> ThreadedRunner: swap terminal/reward order

- tensorforce/core/networks/layer.py
This fixes "object has no attribute 'weights'" when trying to set weights using a float on a Linear layer
> fix "object has no attribute 'weights'"

- examples/configs/dqn_agent.json
This should address the errors that occur with existing config.
New keys from `default_config` dict have not been migrated yet.
> Revise DQN agent example config for new API

- tensorforce/core/baselines/network_baseline.py
- tensorforce/core/networks/__init__.py
- tensorforce/core/networks/layer.py
- tensorforce/core/networks/network.py
- tensorforce/models/distribution_model.py
- tensorforce/models/model.py
- tensorforce/models/pg_log_prob_model.py
- tensorforce/models/pg_model.py
- tensorforce/models/pg_prob_ratio_model.py
- tensorforce/models/q_demo_model.py
- tensorforce/models/q_model.py
Attempt#1 for handling dropout. Background as I know it: dropout should be applied as an additional layer (1) after the input layer, (2) after any dense layers. For Lstm layers, dropout is handled internally by TensorFlow w/ a different mechanic, so should be passed as an argument (as it currently is). AFAIK you don't use dropout w/ Conv2d ([to investigate](https://www.reddit.com/r/MachineLearning/comments/42nnpe/why_do_i_never_see_dropout_applied_in/)). So an example: `[{type: 'dropout', rate: .5}, {type: 'lstm', dropout=.5, ...}, {type: 'dense', ...}, {type: 'dropout', rate: .5}]`
The dropout layers (`tf.layers.dropout` & `tf.contrib.rnn.DropoutWrapper`) take a `training` `tf.placeholder` argument. Usually `tf.placeholder_with_default(False, ...)` so we're forced to explicitly activate …
> Add Dropout layer, Lstm dropout handling, pass training placeholder during layer.apply()

- examples/configs/dqn_agent.json
- tensorforce/util.py
Should resolve the `ValueError` on `obj.rsplit()` when an unknown agent name is provided.
Example failure stimulus:
`python examples/openai_gym.py CartPole-v0 -a PPOAgent -c examples/configs/ppo_agent.json -n examples/configs/ppo_network.json` 
In the above case `PPOAgent` is not a valid option (it should be `ppo_agent` in the revised API) and we receive a non-intuitive error message:
`ValueError: not enough values to unpack (expected 2, got 1)`
With this fix, if the object string is not found, it will report a list of valid options.
> Enhanced error handling for unknown objects

- examples/configs/vpg_network_lstm.json
Added missing size key for LSTM layer (VPG example config)
> Minor: fix VPG LSTM example config

- tensorforce/core/networks/layer.py
Module name was incorrect, was never called by network layers.
> Fix regularization in layer.py

- tensorforce/models/model.py
This adds histograms for the States, Actions, and reward input values if "inputs" is added to the labels of the summary_specs
> add summary_spec for 'inputs' show states,actions,rewards

- tensorforce/agents/agent.py
Looks like a "disabled" `batched_observe` attr is expected to be `None` (rather than 0) the way it's handled elsewhere in `agent.py`. Makes consistent in this location.
> Check self.batched_observe is not None

- examples/quickstart.py
- tensorforce/contrib/openai_gym.py
It might be desirable to visualize the training of agents for two reasons. 
* A person might get a better understanding of the agent's performance by eyeballing the training process rather than the scalar reward. 
* It would be visualizing appealing for demo purposes
Thus, I added a simple parameter to enable such feature over gym's environment. One could use 
``env = OpenAIGym('CartPole-v0', visualize=True)``
to visualize the training process.
> Visualizing gym training

- tensorforce/agents/agent.py
- tensorforce/contrib/openai_gym.py
I was trying to run the [quickstart code on ReversedAddition-v0](https://gist.github.com/vwxyzjn/d906703cdd96f84808c40a40aa8fe64e),
but I got the following error message:
```python
Traceback (most recent call last):
File "<ipython-input-1-411cd64b2471>", line 1, in <module>
runfile('F:/grad school/tensorforce/tensorforce/examples/quickstart.py', wdir='F:/grad school/tensorforce/tensorforce/examples')
File "C:\Users\costa\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
execfile(filename, namespace)
File "C:\Users\costa\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
exec(compile(f.read(), filename, 'exec'), namespace)
File "F:/grad school/tensorforce/tensorforce/examples/quickstart.py", line 84, in <module> …
```
> Fix a bug with generating multiple actions

- tensorforce/core/memories/replay.py
I believe the buffer indices will get out of sync in the current implementation should `set_memory()` be called instead of `add_observation()`. This fix has not been fully tested.
> Update index upon set_memory()

- examples/quickstart.py
Minor update: Might be helpful for those using `quickstart.py` to be aware of the need to adapt discrete OpenAI gym observation spaces to the tensor of floats required by existing TensorForce layers. Added brief note but feel free to adjust (eg. drop identification text) as appropriate.
> quickstart guidance re: embedding for gym discrete obs space

- examples/quickstart.py
The keyword arguments for `PPOAgent` were apparently outdated.
> Fix quickstart.py

- examples/ale.py
Calculation of the step rate references an undefined variable in Runner. Maybe this variable used to exist but is not there in 0.3.3. It looks like r.timestep does the same thing.
> ale.py crashes due to wrong variable referenced in episode_finished

- examples/ale.py
This PR switches to named rather than positional arguments to eliminate confusion.
> ale.py transposes timesteps and episodes arguments when calling Runner.run

- tensorforce/core/networks/__init__.py
- tensorforce/core/networks/complex_network.py
- tensorforce/core/networks/layer.py
- tensorforce/core/networks/network.py
ComplexNetwork basic implementation:
network_spec_CL_selu_cp = [ 
[
dict(type='input', inputs=['state']),
dict(type='dense', size=50, activation='selu', skip=False,l1_regularization=.00,l2_regularization=.0002),
dict(type='dense', size=25, activation='selu', skip=False,l1_regularization=.00,l2_regularization=.0002),
dict(type='dueling', size=3, activation='none', output=('expectation1','advantage1','mean_advantage2'),
summary_labels=['activations','expectation','advantage','mean_advantage']),               
dict(type='output', output='skip'),
dict(type='dense', size=3, activation='selu', skip=False,l1_regularization=.00,l2_regularization=.0002),
dict(type='input', inputs=['*','skip']),            
dict(type='dense', size=3, activation='selu', …
> Complex Network Implementation

- tensorforce/core/explorations/constant.py
- tensorforce/core/explorations/epsilon_anneal.py
- tensorforce/core/explorations/epsilon_decay.py
- tensorforce/core/explorations/exploration.py
- tensorforce/core/explorations/linear_decay.py
- tensorforce/core/explorations/ornstein_uhlenbeck_process.py
- tensorforce/models/model.py
- Model.action_exploration was not defined -> changed it to fn_action_exploration
- This lead to a couple of other hidden problems in the Exploration classes where sometimes, an int was assigned to a shape-parameters in a tf function, which lead to runtime errors.
- Changed num_actions in tf_explore to action_shape to account for that.
- also had to add a few casts (int and float) to make sure tf types are not conflicting (sometimes, when a default value for a function's parameter is 0.0, it changes it to int=0)
- pytests are all "pass"
> Fixed problems with exploration.

- tensorforce/core/networks/layer.py
- tensorforce/util.py
Added swish activation as well as learnable Beta.  Beta parameter can also be added as a constant through the new "activation_kwargs".  A few new TF activations added:
lrelu/leaky_relu: kwargs 'alpha' can be set for leaky slope
crelu
softsign
kwargs supports the follow:
{'beta': float|int|'learn'} # for beta factor on input
{'alpha': float|int}   # For leaky Relu
{'max': float|int}   # Clip maximum input to activation at "max"
{'min': float|int}   # Clip minimum input to activation at "min"
min/max have been added to clip the input values.  So for example, if you want a tf.nn.relu6, use a relu with a {'max': 6.0}.
New summary_labels 'beta' will show a scalar graph in tensorflow of the learned beta parameter.
> Learnable Beta plus a few more TF activation functions

- docs/index.rst
- docs/runner.md
- examples/ale.py
- examples/lab_main.py
- examples/maze_explorer.py
- examples/openai_gym.py
- examples/openai_gym_async.py
- examples/openai_universe.py
- examples/quickstart.py
- examples/unreal_engine.py
- tensorforce/execution/runner.py
- tensorforce/tests/base_test.py
- tensorforce/tests/test_quickstart_example.py
- tensorforce/tests/test_tutorial_code.py
A conversation I'd had earlier with @AlexKuhnle - in order to do cross-validation, or alternating train/test, we came to doing this:
```python
runner = Runner(agent=agent, environment=env)
runner.run(timesteps=...)
next_state, terminal = env.reset(), False
while not terminal:
next_state, terminal, reward = env.execute(agent.act(next_state, deterministic=True))
```
With the current TensorForce code, the Test segment will fail because agent & model will have been closed automatically (in the end of `runner.run()`). For consideration: this PR which requires manually closing `runner`, or possibly a method argument such as `auto_close=True`.
> Runner requires manual call to close() so calling-code can work with "dirty" runner

- examples/maze_explorer.py
Hello, I hope I am following the right procedure here. This is my first pull request. This fixes the following error:
```AttributeError: 'Runner' object has no attribute 'total_timesteps'```
Also the maze explorer example only works in mode 1. Mode 0 throws another error. I will have a look at this.
> Fixed: steps per second calculation maze explorer

- examples/maze_explorer.py
Another small fix in the maze explorer example. I suspect this bug was caused by a paste and copy mistake.
> Fixed: maze explorer there is no attribute args.monitor

- examples/threaded_ale.py
- examples/unreal_engine.py
- tensorforce/agents/agent.py
- tensorforce/contrib/unreal_engine.py
- tensorforce/core/distributions/categorical.py
- tensorforce/core/preprocessing/grayscale.py
- tensorforce/environments/__init__.py
- tensorforce/environments/environment.py
- tensorforce/execution/__init__.py
- tensorforce/execution/base_runner.py
- tensorforce/execution/runner.py
- tensorforce/execution/threaded_runner.py
- tensorforce/tests/base_agent_test.py
- tensorforce/tests/base_test.py
- tensorforce/tests/test_constant_agent.py
- tensorforce/tests/test_ppo_agent.py
- tensorforce/tests/test_random_agent.py
- tensorforce/util.py
Introduced BaseRunner class.
Restructured existing Runner classes (Runner and ThreadedRunner) to both inherit from BaseRunner.
Unified the interfaces used to control these classes and to handle per-episode and per-n-episode reporting.
Added multi-threaded testing to random and constant agent tests (configurable for all agents via run_type flag).
Removed some tf deprecation WARNINGS.
> Unify Runner classes via BaseRunner parent class

- examples/unreal_engine.py
- tensorforce/agents/agent.py
- tensorforce/agents/learning_agent.py
- tensorforce/core/preprocessing/preprocessor.py
- tensorforce/core/preprocessing/preprocessor_stack.py
- tensorforce/core/preprocessing/running_standardize.py
- tensorforce/core/preprocessing/sequence.py
- tensorforce/execution/runner.py
- tensorforce/execution/threaded_runner.py
- tensorforce/models/model.py
- tensorforce/tests/base_agent_test.py
- tensorforce/tests/base_test.py
- tensorforce/tests/test_dqn_agent.py
Fixed sequence and running_standardize preprocessors in memory branch.
Bug fix: model.reset() has to return dict instead of list for self.internals_init.
Fixed counter some stats for Runner/ThreadedRunner.
Fixed some comments (e.g. network vs network_spec) due to new variable naming scheme.
> Sequence and running_standardize preprocessors

- tensorforce/core/networks/layer.py
For consideration. I'm experimenting w/ LSTMCell's `cell_clip=3` param as a way to mitigate _very_ long time-series sequences (vanishing/exploding gradient) from something [I'd read](https://arxiv.org/pdf/1504.01482.pdf). Grain of salt, I'm no expert, so LMK if I'm barking up the wrong tree. Anyway, I'm using this commit https://github.com/lefnire/tensorforce/commit/c33a2648702f6efb29549c98a0adacb47edc291d so I can hyper-search over `cell_clip=[bounded]` & `use_peepholes=[bool]`. I'm thinking maybe it'd just be better to have `lstmcell_args=dict()` which can take any arg LSTMCell would take.
> internal_lstm: allow passing arbitrary args to LSTMCell()

- README.md
The sampling_body method in replay.py uses tf.while_loop and is given a parameter named as maximum_iterations. This parameter is introduced in Tensorflow version 1.5.  If Tensorflow 1.4 is used for DQN and similar agents, we get unknown args 'maximum_iteration' error
> Mentioning minimum TF version for  Tensorforce

- FAQ.md
- tensorforce/models/distribution_model.py
- tensorforce/models/dpg_target_model.py
- tensorforce/models/memory_model.py
- tensorforce/models/model.py
- tensorforce/models/pg_model.py
- tensorforce/models/q_model.py
- tensorforce/tests/test_model_save_restore.py
- tensorforce/util.py
This change introduces the mixin `SavableComponent` that model
components that are to be saved or restored independently from the
model should extend from.
The Model calls `register_saver_ops` of each savable component when
computation graph is constructed and save operations can be added to
it.
Note that with this change the save and restore of the savable
components need to be called explicitly. Model's save, restore and
checkpoint functionality does not delegate to the savable components'
save and restore methods.
A simple recipe to train/preload embeddings can be found in
TestModelSaveRestore.test_pretrain_network
> Independent save and restore of model components

- examples/configs/dqn_ue4.json
- examples/configs/dqn_visual.json
- examples/openai_gym.py
- tensorforce/agents/agent.py
- tensorforce/agents/constant_agent.py
- tensorforce/agents/ddpg_agent.py
- tensorforce/agents/dqfd_agent.py
- tensorforce/agents/dqn_agent.py
- tensorforce/agents/dqn_nstep_agent.py
- tensorforce/agents/learning_agent.py
- tensorforce/agents/naf_agent.py
- tensorforce/agents/ppo_agent.py
- tensorforce/agents/random_agent.py
- tensorforce/agents/trpo_agent.py
- tensorforce/agents/vpg_agent.py
- tensorforce/contrib/remote_environment.py
- tensorforce/contrib/sanity_check_specs.py
- tensorforce/contrib/unreal_engine.py
- tensorforce/models/memory_model.py
- tensorforce/models/model.py
- tensorforce/tests/test_vpg_multithreaded.py
- tensorforce/util.py
Minor refactoring for the model.py:setup() method.
Cleaned it up a little and broke it down into smaller, more comprehensive chunks:
- init graph
- start server
- build graph
- saver
- summaries
- scaffold
- session-hooks
- session
Added sanity checkers and pre-processors for some spec-dicts (state, action, execution) to contrib/sanity_check_specs.py. This is to keep spec-logic and sanity checking in one place. Other specs can be added.
This is in preparation of the upcoming execution/distributed RL changes.
Test are all pass.
Next, I'll go through running a distributed DQN agent (bundled mode) and see what needs to be done with the memories for making distributed work. But maybe it's already ok.
Then I'll add more and more distributed/execution options.
> Cleanup and decomposition of model.py:setup() in preparation of "distributed/execution"-project(s)

- tensorforce/contrib/sanity_check_specs.py
- tensorforce/core/memories/memory.py
- tensorforce/core/memories/prioritized_replay.py
- tensorforce/core/memories/queue.py
- tensorforce/core/memories/replay.py
- tensorforce/core/networks/layer.py
- tensorforce/core/optimizers/__init__.py
- tensorforce/core/optimizers/global_optimizer.py
- tensorforce/core/optimizers/optimizer.py
- tensorforce/core/optimizers/tf_optimizer.py
- tensorforce/environments/__init__.py
- tensorforce/models/distribution_model.py
- tensorforce/models/dpg_target_model.py
- tensorforce/models/memory_model.py
- tensorforce/models/model.py
- tensorforce/models/pg_model.py
- tensorforce/models/q_demo_model.py
- tensorforce/models/q_model.py
- tensorforce/models/q_naf_model.py
- tensorforce/tests/base_agent_test.py
- tensorforce/tests/test_model_save_restore.py
- tensorforce/tests/test_tutorial_code.py
- tensorforce/tests/test_vpg_baselines.py
- tensorforce/tests/test_vpg_memories.py
- tensorforce/tests/test_vpg_multithreaded.py
- tensorforce/tests/test_vpg_optimizers.py
Major refactor in model.py.initialize: Split, renamed and further packaging of sub-tasks by the model's setup function. This will make it easier to write sub-classes for `Model`. Added some missing doc-strings. 
Moved global counters into a cleaner tf.get_variable-logic (instead tf.Variable).
Slight Memory-classes refactor. Moved tf function creation into its own setup function called by init.
Optimizers: Some commenting, removed get_wrapper (replaced by functools.partial).
> Further cleanup of model.py:setup().

- docs/index.rst
- docs/runner.md
- examples/ale.py
- examples/lab_main.py
- examples/openai_universe.py
- examples/threaded_ale.py
- tensorforce/models/model.py
- tensorforce/tests/test_reward_estimation.py
Commit reinforceio/tensorforce@ec7c970 modified some
agent/model arguments.
This commit fixes some uses of the API that were still using the
old argument names
Changed:
states_spec to states
actions_spec to actions
network_spec to network
> Finish API changes to remove _spec

- tensorforce/core/memories/queue.py
Fix for #388.  When queue.capacity is an np.int64, the comparison leads to an np.bool_ type, rather than a python bool, which is what's necessary for the initializer, which is a tf.bool.
> Initialize terminal memory to match tensorflow's expected type

- tensorforce/models/model.py
Otherwise the constructor of Preprocessor complains that the kwarg 'shape' is not set.
> Also pass shape to single preprocessers not just stacked ones

- examples/openai_gym.py
- tensorforce/execution/runner.py
- tensorforce/execution/threaded_runner.py
A simple implementation to allow the runner to test an agent on an environment without learning. Loading weights from file and running the agent on an environment is then simply like the enjoy_scripts in openai/baselines.
P.S. Thanks for this library, is is absolutely amazingly clean and well designed. I would love to contribute to this in the future.
I implemented the test flag in openai_gym.py for now, but it can easily be added to all other examples as soon as you guys are happy with my idea.
> Implement testing flag to runner to evaluate agent with runner.

- tensorforce/models/model.py
- tensorforce/tests/test_model_save_restore.py
Resets the buffer index upon restore, ensuring the model is consistent
with the agent's behavior - starting a new episode.
This fixes the following error which occurs on attempt to restore:
InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [30,1], indices.shape [21], params.shape [100,1]
[[Node: ppo/observe-timestep/store/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@ppo/initialize/latest/initialize/state-state"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/state-state, ppo/observe-timestep/store/mod, ppo/strided_slice, ^ppo/observe-timestep/store/AssignSub)]]
> Fix for restore from checkpoint

- examples/openai_gym.py
- tensorforce/execution/runner.py
- tensorforce/execution/threaded_runner.py
This is especially useful when analyzing the visualization of performance. Running it at normal speed is usually too fast to see what is going on. Like this, it is possible to set --sleep x (seconds, e.g. 0.05 ) in order to make the runner sleep before continuing.
If you do not like the scaling of the sleep representation of time (x vs. 1/x), we can change that to something more useful. I just thought it might make sense to allow the user to choose arbitrary numbers (never restrict too much if you do not know what people are doing with it). We can discuss this here if necessary.
> Implement sleep parameter to runner to allow slowing down execution

- tensorforce/core/memories/latest.py
- tensorforce/core/memories/queue.py
- tensorforce/core/memories/replay.py
- tensorforce/tests/test_memory.py
This addresses issue #433. 
The episode_indices array was not properly updated leading to under-utilization of the buffer and inaccurate episode and timesteps retrieval when the capacity was not perfectly aligned with the episode length.
> Fix the queue-based memories

- tensorforce/contrib/ale.py
- tensorforce/contrib/deepmind_lab.py
- tensorforce/contrib/game_2048.py
- tensorforce/contrib/openai_gym.py
- tensorforce/contrib/pygame_learning_environment.py
- tensorforce/contrib/unreal_engine.py
- tensorforce/environments/environment.py
in #438 I raised the issue of actions not making sense (passing multiple actions to a step) and noted that many user implemented environments (in particular ale, 2048, and unreal engine) didn't actually implement this action. Furthermore, the requirement for a dictionary return also didn't make sense, so I decided to change this. 
In order to normalize things (to make sense with what we think of when we choose actions in the Markov Decision Process), I've deleted this functionality and changed the documentation to make more sense and be more consistent. 
Most environments have remained unchanged. However, for openai_gym, the implementation has been changed. Importantly, as it was implemented, passing in lists was impossible (as you can't pass in a list of actions for env.step) so this …
> Action clarified 

- .gitignore
- tensorforce/environments/openai_gym.py
Works now with all the standard gym environments. Does not yet work with my custom one, having 
```
self.observation_space = spaces.MultiDiscrete([1,2,3])
```
Getting the following error
```
...
~/tensorforce/tensorforce/util.py in valid_value_spec(value_spec, value_type, accept_underspecified, return_normalized)
390             if not isinstance(num_values, int):
391                 raise TensorforceError.type(
--> 392                     name=(value_type + ' spec'), argument='num_values', value=num_values
393                 )
394             if accept_underspecified:
TensorforceError: Invalid type for state spec argument num_values: <class 'numpy.uint32'>.
```
> Fixed an error with referencing the Monitor class. Still needs some work regarding spacial cases of gym environments.

- tensorforce/agents/agent.py
- test/test_agents.py
fixes typo in Agent.__init__ resulting in an exception when seed is not None.
added unit test to test_agent, which simply instantiates an agent with a non-trivial seed
question: is this the right place for a unit test like this ? is there a better way to test the instantiation with a seed ?
> fix Agent seeding

- tensorforce/environments/environment_process_wrapper.py
This is a wrapper for multicore parallel training using multiprocessing.
To use it with the parallel runner, simply do as you would have before, but wrapping the environments with `ProcessWrapper`
An usage example:
```python3
from tensorforce.execution import ParallelRunner
from tensorforce.environments.environment_process_wrapper import ProcessWrapper
n_env = 8
envs = []
for _ in range(n_env):
envs.append(ProcessWrapper(Environment.create(...)))
agent = ...
agent.initialize()
runner = ParallelRunner(agent=agent, environments=envs)
runner.run(num_episodes=100, sync_episodes=False)
runner.close()
```
On a custom gym environment of mine (the one I used in this paper https://arxiv.org/abs/1910.07788), this wrapper speeds up the execution by a factor of 2.2 as you can see here, with 16 …
> Multiprocessing wrapper

- examples/quickstart.py
tf.logging was removed in TF 2.0. This commit fixes the error when running the quickstart.py which uses tf.logging.
> Replace tf.logging with Python logging module.

- benchmarks/configs/dqn.json
I added in the benchmarks/configs folder the dqn configuration following the one used by tf-agents in their tutorial. 
To actually compare the 2 implementations, the Cartpole-v0 env should be used and the training time set to 20000 timesteps. The dqn config now also uses the network definition used (1-layer, 100 neurons) by tf-agents. 
It wasn't quite obvious to me if and how these settings should/could baked into the benchmark. So I'm not sure of this additional config is actually helpful or not.
> dqn config

- run.py
- tensorforce/agents/agent.py
- tensorforce/core/utils/json_encoder.py
Implemented a simple JSONEncoder to serialize numpy floating point
numbers, which doesn't work otherwise. This is necessary for saving
an agent. More cases can be added once they are identified not working.
> Support for JSON-encoding specific numpy types

- tensorforce/agents/agent.py
The filename truncation should be different, depending if the filename ends with ".hdf5" or ".h5"
> corrected filename truncation for h5-files

- tensorforce/agents/agent.py
- tensorforce/core/models/model.py
Hi,
I switched the checkpoint saving method from "write" to "save", as write doesn't create a "checkpoint" file which allows restoring afterwards (see https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#write). Was it intentional to use write?
I also added an error message when there's no checkpoint, and simplified the code to extract the filename. Nothing really fancy.
Thanks!
Benjamin
> Save checkpoint instead of write

- tensorforce/environments/environment.py
Fixed an issue with unpacking experiences (e.g., states, terminal, reward, seconds) from a remote environment.
Without unpacking the seconds, which is added by each worker environment, [this assertion](https://github.com/tensorforce/tensorforce/blob/67424fcc2f2c8d92dce6f163fad1fbe0c338fa1d/tensorforce/agents/recorder.py#L502) is failed since seconds will be a part of states.
I was intending to raise an issue but debugging was faster
> Unpacking Experience Fix for Remote Environments.

- tensorforce/core/distributions/categorical.py
- test/test_policies.py
- test/unittest_environment.py
Hi @AlexKuhnle , 
in your commit to https://github.com/tensorforce/tensorforce/issues/783 I noticed there was a problem while using skip_linear in conjunction with an environment with defines the actions without the optional shape parameter. I had a look into it and (if I am not mistaken) there was some unnecessary code which caused the error. I removed it and additionally added a fitting unittest.
> Fixed skip_linear if not used with shape parameter in action_values

- tensorforce/environments/environment.py
The assertion contained in `_check_states_output()` fails if `_states` is nested since the `len()` operator only returns the high-level value for `dict()`.
> make states ArrayDict in case _states is a nested dict.

- requirements-all.txt
- requirements.txt
- tensorforce/environments/openai_gym.py
With higher gym versions, it shows :
`AttributeError: module 'gym.wrappers' has no attribute 'Monitor'`
I attempt to fix it, but it throwed further errors that makes it non working.
In some versions, it's error about `gym.envs.registry.env_specs` that needs to be changed to `gym.envs.registry` in whole `openai_gym.py` file, but there was also errors about `assert spec is not None` and it was done, as API to specs changed.
> Set maximum `gym` version for compatibility reasons.

- tensorforce/core/optimizers/tf_optimizer.py
- tensorforce/core/utils/dicts.py
- Use legacy optimizers for compatibility with TF 2.11.1.
- Fix `NotImplementedError` when loading an agent.
> Use legacy optimizers and fix NotImplementedError when loading an agent
